const BOX_ONES = 'BOX_ONES';
const BOX_TWOS = 'BOX_TWOS';
const BOX_THREES = 'BOX_THREES';
const BOX_FOURS = 'BOX_FOURS';
const BOX_FIVES = 'BOX_FIVES';
const BOX_SIXES = 'BOX_SIXES';

const BOX_TRIPS = 'BOX_TRIPS';
const BOX_QUADS = 'BOX_QUADS';
const BOX_FULL_HOUSE = 'BOX_FULL_HOUSE';
const BOX_SM_STRAIGHT = 'BOX_SM_STRAIGHT';
const BOX_LG_STRAIGHT = 'BOX_LG_STRAIGHT';
const BOX_CHANCE = 'BOX_CHANCE';
const BOX_YAHTZEE = 'BOX_YAHTZEE';

const ALL_BOXES = [
  BOX_ONES,
  BOX_TWOS,
  BOX_THREES,
  BOX_FOURS,
  BOX_FIVES,
  BOX_SIXES,
  BOX_TRIPS,
  BOX_QUADS,
  BOX_FULL_HOUSE,
  BOX_SM_STRAIGHT,
  BOX_LG_STRAIGHT,
  BOX_CHANCE,
  BOX_YAHTZEE
];
